"""Layer 2: training queue, adapter selection and forgetting (SPEC 7).

The adapter is a cache of *behaviour* (voice, register, terminology,
procedures). The rules implemented here:

* eligibility — only TRAINABLE claims or user corrections, distance ≤ 1, no
  stale dependency, no reference-only source (SPEC 7.1);
* batch composition — interleaved replay > 0 and peer-derived material strictly
  below one half (I3, I6);
* candidates — every candidate is initialised from the **base model**; nothing
  is inherited across generations but the recipe (I6);
* gate — improvement on memory-derived questions, bounded general loss and
  abstention outside memory, on a test set generated **for this generation**;
  reusing a test set is refused, because it inflates the observed gain of the
  selected candidate (Dwork et al., 2015);
* forgetting — an adapter trained on a stale example is retired and
  regenerated without it; approximate unlearning is never claimed (SPEC 7.8).

Trainers are pluggable. ``MockTrainer`` + ``MockEvaluator`` simulate adapters
with a latent true quality and a noisy gate so that selection bias can be
studied (H-C15); ``MLXLoRATrainer`` drives ``mlx_lm`` on Apple Silicon and is
experimental (not exercised in CI).
"""

from __future__ import annotations

import json
import math
import random
import subprocess
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Iterable, Protocol, Sequence

from .canonical import digest16
from .claims import ClaimType, Maturity
from .errors import InvariantViolation
from .params import DEFAULT, Params
from .wiki import Wiki

__all__ = [
    "Example",
    "Recipe",
    "Batch",
    "Adapter",
    "GateScores",
    "TestSet",
    "eligible",
    "ExampleBuilder",
    "BatchComposer",
    "Trainer",
    "Evaluator",
    "MockTrainer",
    "MockEvaluator",
    "TestSetRegistry",
    "Gate",
    "AdapterManager",
    "MLXLoRATrainer",
]


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Example:
    kind: str  # "style" | "qa" | "preference_pair" | "replay" | "general"
    prompt: str
    response: str
    rejected: str = ""
    claim_ids: tuple[str, ...] = ()
    origin: str = "self"  # "self" | "social"
    epistemic_distance: int = 0
    human_source: str = "self"
    generator: str = "base"  # "base" | "adapter:<id>" — text generated by an adapter is forbidden

    @property
    def example_id(self) -> str:
        return digest16({"k": self.kind, "p": self.prompt, "r": self.response, "x": self.rejected})


@dataclass(frozen=True)
class Recipe:
    rank: int = 8
    alpha: int = 16
    lr: float = 1e-4
    epochs: int = 2
    replay_fraction: float = DEFAULT.replay_fraction
    general_fraction: float = DEFAULT.general_fraction
    social_fraction: float = 0.0
    seed: int = 0

    @property
    def recipe_id(self) -> str:
        return digest16(asdict(self))


@dataclass
class Batch:
    examples: list[Example]
    recipe: Recipe

    @property
    def social_share(self) -> float:
        return sum(e.origin == "social" for e in self.examples) / max(1, len(self.examples))

    @property
    def replay_share(self) -> float:
        return sum(e.kind == "replay" for e in self.examples) / max(1, len(self.examples))


@dataclass
class Adapter:
    adapter_id: str
    base_model: str
    recipe: Recipe
    example_ids: tuple[str, ...]
    init_from: str  # always the base model (I6)
    generation: int
    path: str = ""
    true_quality: float | None = None  # simulation only
    contains_facts: bool = False


@dataclass
class GateScores:
    wiki_gain: float  # points over the current adapter / base on memory questions
    general_loss: float  # points lost on the general benchmark
    abstain_rate: float  # fraction of out-of-memory questions where it abstains

    def passes(self, params: Params = DEFAULT) -> bool:
        return (self.wiki_gain >= params.gate_min_gain and self.general_loss <= params.gate_max_loss
                and self.abstain_rate >= params.gate_min_abstain)


@dataclass(frozen=True)
class TestSet:
    __test__ = False  # not a pytest class
    test_id: str
    generation: int
    questions: tuple[tuple[str, str], ...]  # (question, reference answer)
    out_of_memory: tuple[str, ...] = ()


# ---------------------------------------------------------------------------
# Eligibility and example building
# ---------------------------------------------------------------------------

def eligible(example: Example, wiki: Wiki, params: Params = DEFAULT) -> bool:
    """SPEC 7.1 plus I1/I3. Returns False rather than raising: callers filter."""
    if example.generator != "base":
        return False
    if example.epistemic_distance > params.epistemic_max_share_train:
        return False
    if example.kind in {"replay", "general"}:
        return True
    if example.kind == "preference_pair":
        return bool(example.rejected)
    if not example.claim_ids:
        return False
    for cid in example.claim_ids:
        c = wiki.claims.get(cid)
        if c is None or c.maturity != Maturity.TRAINABLE or wiki.graph.is_stale(f"claim:{cid}"):
            return False
        if not c.behavioural:
            return False
        if any(wiki.policy.rule_for(a.source).reference_only for a in c.anchors):
            return False
        if example.kind == "style" and not all(wiki.policy.rule_for(a.source).authored_by_user for a in c.anchors):
            return False
    return True


@dataclass
class ExampleBuilder:
    wiki: Wiki

    def from_claims(self) -> list[Example]:
        out: list[Example] = []
        for c in sorted(self.wiki.trainable(), key=lambda x: x.claim_id):
            if c.type == ClaimType.STYLE:
                out.append(Example("style", "Write in my usual voice.", c.text, claim_ids=(c.claim_id,),
                                   epistemic_distance=c.provenance.epistemic_distance))
            else:
                q = ("How do you usually do this?" if c.type == ClaimType.PROCEDURE else "What do you prefer here?")
                # The reference answer IS the anchored claim, whose span was verified
                # when the claim reached ANCHORED (SPEC 7.2.2).
                out.append(Example("qa", q, c.text, claim_ids=(c.claim_id,),
                                   epistemic_distance=c.provenance.epistemic_distance))
        return out

    @staticmethod
    def correction(before: str, after: str, prompt: str = "Rewrite as I would.") -> Example:
        return Example("preference_pair", prompt, after, rejected=before, epistemic_distance=0)


@dataclass
class BatchComposer:
    params: Params = DEFAULT

    def compose(self, new: Sequence[Example], replay: Sequence[Example], general: Sequence[Example],
                social: Sequence[Example], recipe: Recipe, wiki: Wiki) -> Batch:
        if recipe.replay_fraction <= 0:
            raise InvariantViolation("I6", "every batch must include interleaved replay (fraction > 0)")
        if recipe.social_fraction >= self.params.social_train_fraction_hard:
            raise InvariantViolation("I3", "peer-derived material must stay strictly below one half")
        if not replay:
            raise InvariantViolation("I6", "replay pool is empty; cannot honour interleaved replay")
        rng = random.Random(recipe.seed)
        own = [e for e in new if eligible(e, wiki, self.params) and e.origin == "self"]
        if not own:
            raise ValueError("no eligible own examples: nothing to train")
        soc = [e for e in social if eligible(e, wiki, self.params) and e.origin == "social" and e.human_source]
        n_own = len(own)
        # Solve shares so that replay/general/social reach their target fractions of the total.
        rest = max(1e-9, 1.0 - recipe.replay_fraction - recipe.general_fraction - recipe.social_fraction)
        total = n_own / rest
        n_rep = max(1, round(total * recipe.replay_fraction))
        n_gen = round(total * recipe.general_fraction) if general else 0
        n_soc = min(len(soc), round(total * recipe.social_fraction))
        pick = lambda pool, n: [pool[rng.randrange(len(pool))] for _ in range(n)] if pool and n > 0 else []  # noqa: E731
        examples = own + pick(list(replay), n_rep) + pick(list(general), n_gen) + soc[:n_soc]
        batch = Batch(examples, recipe)
        if batch.social_share >= self.params.social_train_fraction_hard:
            raise InvariantViolation("I3", f"social share {batch.social_share:.2f} reached the hard cap")
        return batch


# ---------------------------------------------------------------------------
# Trainers and evaluators
# ---------------------------------------------------------------------------

class Trainer(Protocol):
    def train(self, base_model: str, batch: Batch, generation: int) -> Adapter:  # pragma: no cover - protocol
        ...


class Evaluator(Protocol):
    def evaluate(self, adapter: Adapter, test: TestSet, baseline: Adapter | None) -> GateScores:  # pragma: no cover
        ...


@dataclass
class MockTrainer:
    """Simulated trainer: an adapter's latent quality is a deterministic function
    of its recipe plus noise. SIMULATION ONLY — not evidence about real training."""

    sd_true: float = 10.0
    seed: int = 0

    def train(self, base_model: str, batch: Batch, generation: int) -> Adapter:
        r = batch.recipe
        rng = random.Random(f"{self.seed}|{r.recipe_id}|{generation}")
        q = 10.0 - 3.0 * abs(math.log2(max(r.rank, 1)) - 3.0) - 20.0 * abs(math.log10(r.lr) + 4.0) + rng.gauss(0, self.sd_true)
        q += 4.0 * (r.replay_fraction > 0)  # replay protects old behaviour
        aid = digest16({"b": base_model, "r": r.recipe_id, "g": generation, "ex": sorted(e.example_id for e in batch.examples)})
        return Adapter(aid, base_model, r, tuple(sorted({e.example_id for e in batch.examples})), init_from=base_model,
                       generation=generation, true_quality=q)


@dataclass
class MockEvaluator:
    """Noisy gate measurement of the latent quality.

    ``reliability`` is the correlation between measured and true gain; a
    *reused* test set adds a per-adapter bias that persists across
    generations, which is what makes reuse inflate the winner's apparent gain.
    """

    reliability: float = 0.5
    sd_true: float = 10.0
    seed: int = 0
    reuse_bias_sd: float = 0.0

    def evaluate(self, adapter: Adapter, test: TestSet, baseline: Adapter | None) -> GateScores:
        rng = random.Random(f"{self.seed}|{adapter.adapter_id}|{test.test_id}")
        rho = max(1e-6, min(1.0, self.reliability))
        noise_sd = self.sd_true * math.sqrt(1 / rho**2 - 1)
        base_q = baseline.true_quality if baseline and baseline.true_quality is not None else 0.0
        bias = random.Random(f"bias|{adapter.recipe.recipe_id}|{test.test_id}").gauss(0, self.reuse_bias_sd) if self.reuse_bias_sd else 0.0
        measured = (adapter.true_quality or 0.0) - base_q + rng.gauss(0, noise_sd) + bias
        return GateScores(wiki_gain=measured, general_loss=max(0.0, rng.gauss(1.0, 0.8)), abstain_rate=min(1.0, max(0.0, rng.gauss(0.9, 0.05))))


# ---------------------------------------------------------------------------
# Fresh test sets and the gate
# ---------------------------------------------------------------------------

@dataclass
class TestSetRegistry:
    __test__ = False  # not a pytest class
    used: dict[str, int] = field(default_factory=dict)  # test_id -> generation

    def fresh(self, wiki: Wiki, generation: int, exclude_examples: Iterable[str], k: int = 32, seed: int = 0) -> TestSet:
        """Questions from anchored claims not used as training examples in this generation."""
        excluded = set(exclude_examples)
        pool = [c for c in wiki.claims.values() if c.anchored and c.claim_id not in excluded]
        rng = random.Random(f"{seed}|{generation}")
        rng.shuffle(pool)
        qs = tuple((f"Q[{generation}]: {c.text[:80]}?", c.text) for c in pool[:k])
        oom = tuple(f"Q[{generation}]: unrelated-{i}-{seed}?" for i in range(max(4, k // 4)))
        tid = digest16({"g": generation, "q": qs, "seed": seed})
        if tid in self.used:
            raise InvariantViolation("I6", "test set already used by a previous generation")
        self.used[tid] = generation
        return TestSet(tid, generation, qs, oom)

    def assert_unused(self, test: TestSet, generation: int) -> None:
        g = self.used.get(test.test_id)
        if g is not None and g != generation:
            raise InvariantViolation("I6", f"test set {test.test_id} was used in generation {g}; reuse inflates the selected gain")


@dataclass
class Gate:
    params: Params = DEFAULT

    def choose(self, scored: Sequence[tuple[Adapter, GateScores]]) -> Adapter | None:
        passing = [(a, s) for a, s in scored if s.passes(self.params)]
        if not passing:
            return None
        return max(passing, key=lambda x: (x[1].wiki_gain, x[0].adapter_id))[0]


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

@dataclass
class AdapterManager:
    wiki: Wiki
    base_model: str
    trainer: Trainer
    evaluator: Evaluator
    params: Params = DEFAULT
    registry: TestSetRegistry = field(default_factory=TestSetRegistry)
    current: Adapter | None = None
    history: list[dict] = field(default_factory=list)
    generation: int = 0
    affected_since: int | None = None

    def run_generation(self, new: Sequence[Example], replay: Sequence[Example], general: Sequence[Example],
                       recipes: Sequence[Recipe], social: Sequence[Example] = ()) -> Adapter | None:
        if not 1 <= len(recipes) <= max(1, self.params.n_candidates * 4):
            raise ValueError("number of candidate recipes out of range")
        self.generation += 1
        composer = BatchComposer(self.params)
        candidates: list[Adapter] = []
        used_examples: set[str] = set()
        for r in recipes:
            batch = composer.compose(new, replay, general, social, r, self.wiki)
            a = self.trainer.train(self.base_model, batch, self.generation)
            if a.init_from != self.base_model:
                raise InvariantViolation("I6", "candidate not initialised from the base model")
            candidates.append(a)
            used_examples |= {cid for e in batch.examples for cid in e.claim_ids}
        test = self.registry.fresh(self.wiki, self.generation, used_examples, seed=self.generation)
        scored = [(a, self.evaluator.evaluate(a, test, self.current)) for a in candidates]
        winner = Gate(self.params).choose(scored)
        self.history.append({
            "generation": self.generation,
            "test_id": test.test_id,
            "candidates": [{"adapter": a.adapter_id, "recipe": a.recipe.recipe_id, "gain": s.wiki_gain,
                            "loss": s.general_loss, "abstain": s.abstain_rate, "passes": s.passes(self.params)} for a, s in scored],
            "winner": winner.adapter_id if winner else None,
        })
        if winner is not None:
            self._register(winner, new)
            self.current = winner
            self.affected_since = None
        return winner

    def _register(self, adapter: Adapter, new: Sequence[Example]) -> None:
        g = self.wiki.graph
        anode = f"adapter:{adapter.adapter_id}"
        g.add_node(anode, "adapter")
        for e in new:
            enode = f"example:{e.example_id}"
            if e.example_id not in adapter.example_ids:
                continue
            g.add_node(enode, "example")
            for cid in e.claim_ids:
                cnode = f"claim:{cid}"
                if cnode in g.kinds and enode not in g.children.get(cnode, set()):
                    g.add_edge(cnode, enode)
            if anode not in g.children.get(enode, set()):
                g.add_edge(enode, anode)

    def current_affected(self) -> bool:
        return self.current is not None and f"adapter:{self.current.adapter_id}" in self.wiki.graph.affected_adapters()

    def enforce_forgetting(self) -> bool:
        """Retire the current adapter if affected for more than FORGET_MAX_CYCLES (SPEC 7.8.2)."""
        if not self.current_affected():
            self.affected_since = None
            return False
        if self.affected_since is None:
            self.affected_since = self.wiki.cycle
        if self.wiki.cycle - self.affected_since >= self.params.forget_max_cycles - 1:
            self.wiki.graph.remove(f"adapter:{self.current.adapter_id}")
            self.current = None
            return True
        return False


@dataclass
class MLXLoRATrainer:
    """EXPERIMENTAL: train a LoRA with ``mlx_lm`` on Apple Silicon.

    Not exercised in CI. Writes the batch as JSONL chat data and calls
    ``python -m mlx_lm.lora``. Requires ``pip install mlx-lm``.
    """

    workdir: str
    iters: int = 200
    batch_size: int = 4

    @staticmethod
    def available() -> bool:
        try:
            import mlx_lm  # type: ignore  # noqa: F401
            return True
        except Exception:
            return False

    def export(self, batch: Batch, path: Path) -> None:
        path.mkdir(parents=True, exist_ok=True)
        rows = [{"messages": [{"role": "user", "content": e.prompt}, {"role": "assistant", "content": e.response}]}
                for e in batch.examples if e.kind != "preference_pair"]
        n_valid = max(1, len(rows) // 10)
        (path / "train.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in rows[n_valid:]) + "\n", encoding="utf-8")
        (path / "valid.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in rows[:n_valid]) + "\n", encoding="utf-8")

    def train(self, base_model: str, batch: Batch, generation: int) -> Adapter:
        if not self.available():
            raise RuntimeError("mlx_lm is not installed; use MockTrainer or install mlx-lm on Apple Silicon")
        r = batch.recipe
        out = Path(self.workdir) / f"gen{generation}_{r.recipe_id}"
        data = out / "data"
        self.export(batch, data)
        cmd = [sys.executable, "-m", "mlx_lm.lora", "--model", base_model, "--train", "--data", str(data),
               "--adapter-path", str(out / "adapter"), "--iters", str(self.iters), "--batch-size", str(self.batch_size),
               "--learning-rate", str(r.lr), "--seed", str(r.seed)]
        subprocess.run(cmd, check=True)
        aid = digest16({"b": base_model, "r": r.recipe_id, "g": generation})
        return Adapter(aid, base_model, r, tuple(sorted({e.example_id for e in batch.examples})), init_from=base_model,
                       generation=generation, path=str(out / "adapter"))
